# Generated by Django 4.2.27 on 2026-01-13 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-session'], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening')], default='MORNING', help_text='Session: MORNING or EVENING', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('application', 'date', 'session')},
        ),
    ]
