# Generated by Django 4.2.27 on 2026-01-12 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(help_text='Duration in days')),
                ('max_students', models.IntegerField(default=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, help_text='Requirements and eligibility', null=True)),
                ('skills_gained', models.TextField(blank=True, help_text='Skills students will gain', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(blank=True, limit_choices_to={'role': 'COORDINATOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_internships', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
            ],
            options={
                'verbose_name': 'Internship',
                'verbose_name_plural': 'Internships',
                'ordering': ['-created_at'],
            },
        ),
    ]
