# Generated by Django 4.2.27 on 2026-01-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_internship_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='eligibility',
            field=models.TextField(blank=True, help_text='Eligibility criteria', null=True),
        ),
    ]
