# Generated by Django 6.0.1 on 2026-01-20 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('courses', '0002_course_category'),
        ('internships', '0003_internship_eligibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='application',
            name='internship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internships.internship'),
        ),
    ]
