# Generated by Django 6.0.1 on 2026-01-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='highest_qualification_other',
            field=models.CharField(blank=True, help_text='Custom qualification if Other is selected', max_length=100, null=True),
        ),
    ]
