# Generated by Django 4.2.27 on 2026-01-13 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
        ('accounts', '0003_user_approval_date_user_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch this student belongs to (only for students)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='batches.batch'),
        ),
    ]
