# Generated by Django 4.2.27 on 2026-01-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_approval_date_user_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('COORDINATOR', 'HR Coordinator'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
