# Generated by Django 6.0.1 on 2026-01-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='highest_qualification',
            field=models.CharField(blank=True, choices=[('10TH', '10th Standard'), ('12TH', '12th Standard'), ('HIGH_SCHOOL', 'High School'), ('DIPLOMA', 'Diploma'), ('UG', 'Under Graduate (UG)'), ('PG', 'Post Graduate (PG)'), ('PHD', 'PhD'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
