# Generated by Django 4.2.27 on 2026-01-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, help_text="Student's highest qualification", max_length=255, null=True),
        ),
    ]
