# Generated by Django 4.2.27 on 2026-01-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('WEB', 'Web Development'), ('PYTHON', 'Python Programming'), ('DATA', 'Data Science'), ('AI', 'Artificial Intelligence'), ('APP', 'App Development'), ('CYBER', 'Cyber Security'), ('DESIGN', 'UI/UX Design'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
