# Generated by Django 4.2.27 on 2026-01-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='principal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Principal Email'),
        ),
        migrations.AddField(
            model_name='institution',
            name='principal_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Principal Name'),
        ),
        migrations.AddField(
            model_name='institution',
            name='principal_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Principal Phone'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='College Email'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=200, verbose_name='College Name'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='College Phone'),
        ),
    ]
