# Generated by Django 4.2.27 on 2026-01-19 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0002_institution_principal_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.RemoveField(
            model_name='institution',
            name='principal_email',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='principal_name',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='principal_phone',
        ),
        migrations.AddField(
            model_name='institution',
            name='hr_coordinator_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='HR Coordinator Email'),
        ),
        migrations.AddField(
            model_name='institution',
            name='hr_coordinator_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='HR Coordinator Name'),
        ),
        migrations.AddField(
            model_name='institution',
            name='hr_coordinator_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='HR Coordinator Phone'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='coordinator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'COORDINATOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='institution',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Company Email'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='companies/'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Company Phone'),
        ),
    ]
