# Generated by Django 4.2.27 on 2026-01-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('background_image', models.ImageField(upload_to='cert_templates/')),
                ('name_x_axis', models.IntegerField(default=400, help_text='X Coordinate (Horizontal)')),
                ('name_y_axis', models.IntegerField(default=300, help_text='Y Coordinate (Vertical)')),
                ('font_size', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='attendance_percentage',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_number',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ISSUED', 'Issued'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20),
        ),
    ]
