# Generated by Django 4.2.27 on 2026-01-13 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0002_certificatetemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='attendance_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Attendance percentage at the time of certificate generation', max_digits=5),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='Admin who issued this certificate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL),
        ),
    ]
